# Generated by Django 5.2.6 on 2025-09-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('nacionality', models.CharField(choices=[('AF', 'Afeganistão'), ('AR', 'Argentina'), ('AU', 'Austrália'), ('BE', 'Bélgica'), ('BR', 'Brasil'), ('CA', 'Canadá'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colômbia'), ('DE', 'Alemanha'), ('DK', 'Dinamarca'), ('EG', 'Egito'), ('ES', 'Espanha'), ('FR', 'França'), ('GR', 'Grécia'), ('IN', 'Índia'), ('IT', 'Itália'), ('JP', 'Japão'), ('KR', 'Coreia do Sul'), ('MX', 'México'), ('NG', 'Nigéria'), ('NL', 'Holanda'), ('PT', 'Portugal'), ('RU', 'Rússia'), ('SE', 'Suécia'), ('TR', 'Turquia'), ('UK', 'Reino Unido'), ('UA', 'Ucrânia'), ('US', 'Estados Unidos'), ('ZA', 'África do Sul')], max_length=2)),
            ],
        ),
    ]
